### ISSUE TITLE
Pleas update the docs

### ISSUE THREAD

**Issue by cm45t3r** [tradalize/core#26]
Hi,

Could you update the README up to the latest version?

- There are two new methods to implement when extending from `Strategy`: `calcSl` and `calcTp`. It would be great to have an example.
- No idea whether to use `checkOpenOnNext` and `checkCloseOnNext`, or `openOnNext` and `closeOnNext` and how to use it.

Thank you.

**Comment by Besmerch123** [comment]
Hi, @cm45t3r )
Thanks for the reminder

Doc updated, I also added some comments to the methods and properties, so now you will have some IntelliSense hints in your editor

Those methods are not actually required to be implemented, you can simply return `undefined` from them and everything will work as it was before. But I can't make them non-abstract, will have errors from the linter. However, abstract methods are technically obligatory to implement according to TS specifications, even though there is a GitHub [issue](https://github.com/microsoft/TypeScript/issues/40635) to make them optional. But the issue is almost 4 years in the Open status, I don't think it will be implemented somewhere near.

Thank you for using this library, hope it helps you with your strategies =)
Have a profitable trades
